version: '3.4'

services:
  webluna:
    image: webluna
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
